"""
K10 Data Preparation — Deduplicate & Z3-Filter
===============================================

Prepares raw k10 candidate data for downstream selection-method fine-tuning:

  1. Load raw k10 data (generated by generate_k10.py / generate_k10_val.ipynb).
  2. **Deduplicate** candidates per sentence — keep only the first occurrence
     of each unique FOL string (by fol_hash).
  3. **Z3-filter** — keep only candidates whose FOL formula can be parsed by Z3
     (execution_rate == 1.0).  This is the strictest filter and ensures all
     candidates are usable by M1 (LE-Vote), M2 (GSC-BLEU), and M3 (GSC-BertScore).
  4. Print before/after statistics.
  5. Save the filtered data alongside the original.

Usage (Python)::

    from src.prepare_k10 import prepare_k10_data
    stats = prepare_k10_data(model="Qwen4b", dataset="val")

Usage (CLI)::

    python src/prepare_k10.py --model Qwen4b --dataset val
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_ROOT = Path(__file__).resolve().parent.parent  # project/code/
DATA_DIR = _ROOT / "data"
RESULTS_BASE = DATA_DIR / "results"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _resolve_k10_paths(model: str, dataset: str) -> dict:
    """Resolve input / output paths for a model+dataset combo.

    Input:  data/results/{model}/k10/{model}_k10_{dataset}.json
    Output: data/results/{model}/k10/{model}_k10_{dataset}_filtered.json
    """
    k10_dir = RESULTS_BASE / model / "k10"
    suffix = dataset.replace("test_", "").replace("test", "")
    tag = f"{model}_k10_{suffix}" if suffix else f"{model}_k10"

    in_path = k10_dir / f"{tag}.json"
    out_path = k10_dir / f"{tag}_filtered.json"

    k10_dir.mkdir(parents=True, exist_ok=True)
    return {
        "in_path": in_path,
        "out_path": out_path,
        "k10_dir": k10_dir,
        "tag": tag,
    }


def _z3_parsable(fol: str, timeout_ms: int = 5_000) -> bool:
    """Return True if *fol* can be parsed by Z3."""
    if not fol or not fol.strip():
        return False
    try:
        from src.eval.z3parser import fol_to_z3
        import z3 as _z3
        ctx = _z3.Context()
        try:
            fol_to_z3(str(fol), timeout_ms, ctx=ctx)
            return True
        finally:
            del ctx
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------


def prepare_k10_data(
    model: str = "Qwen4b",
    dataset: str = "val",
    *,
    z3_timeout_ms: int = 5_000,
    verbose: bool = True,
    save_to_disk: bool = True,
) -> dict:
    """Load raw k10 candidates, deduplicate, Z3-filter, and optionally save.

    Steps (per sentence):
      1. Deduplicate by ``fol_hash`` — keep the first occurrence of each unique FOL.
      2. Z3-filter — keep only candidates whose FOL can be parsed by Z3.

    The filtered data is saved as ``{model}_k10_{dataset}_filtered.json``
    in the same directory as the original k10 data (unless *save_to_disk* is False).

    Parameters
    ----------
    model : str
        Model key ("Qwen4b", "Qwen8b", "Ministral8b").
    dataset : str
        Dataset name ("val", "test", "test_folio", "test_willow").
    z3_timeout_ms : int
        Timeout per Z3 parse check (default 5s).
    verbose : bool
        Print progress and statistics.
    save_to_disk : bool
        If False, skip saving the filtered JSON file and return the data
        directly in the result dict under the ``data`` key.

    Returns
    -------
    dict with keys:
        model, dataset, in_path, out_path,
        n_sentences,          # number of sentences processed
        total_candidates_in,  # candidates before filtering
        total_after_dedup,    # candidates after dedup
        total_after_z3,       # candidates after Z3 filtering
        sentences_with_0,     # sentences with 0 candidates after filtering
        elapsed_sec,
        data,                 # (only when save_to_disk=False) the filtered data list
    """
    paths = _resolve_k10_paths(model, dataset)

    # ---- validate input ----
    if not paths["in_path"].exists():
        raise FileNotFoundError(
            f"K10 data not found: {paths['in_path']}\n"
            f"Run generate_k10_val.ipynb (or generate_k10.py) first."
        )

    # ---- load ----
    with open(paths["in_path"], encoding="utf-8") as f:
        data = json.load(f)

    n_sentences = len(data)
    total_in = sum(len(entry.get("candidates", [])) for entry in data)

    if verbose:
        print("=" * 55)
        print("  K10 DATA PREPARATION")
        print(f"  Model:   {model}")
        print(f"  Dataset: {dataset}")
        print(f"  Input:   {paths['in_path']}")
        print(f"  Output:  {paths['out_path']}")
        print("=" * 55)
        print()
        print(f"  [1] Loaded: {n_sentences} sentences, {total_in} total candidates")
        print(f"      Avg candidates/sentence: {total_in / max(n_sentences, 1):.1f}")

    # ---- stage 1: deduplicate ----
    t0 = time.perf_counter()
    total_dedup = 0
    n_dup_sents = 0

    for entry in data:
        seen_hashes: set = set()
        unique_cands: list = []
        for cand in entry.get("candidates", []):
            h = cand.get("fol_hash")
            if h and h not in seen_hashes:
                seen_hashes.add(h)
                unique_cands.append(cand)
        n_before = len(entry.get("candidates", []))
        n_after = len(unique_cands)
        if n_after < n_before:
            n_dup_sents += 1
        total_dedup += n_after
        entry["candidates"] = unique_cands
        entry["unique_count"] = n_after

    if verbose:
        dup_removed = total_in - total_dedup
        print(f"\n  [2] Deduplication:")
        print(f"      Removed:  {dup_removed} duplicate candidates")
        print(f"      Retained: {total_dedup} unique candidates")
        print(f"      Sentences with duplicates: {n_dup_sents}/{n_sentences}")
        print(f"      Avg unique/sentence: {total_dedup / max(n_sentences, 1):.2f}")

    # ---- stage 2: Z3 filter ----
    total_z3 = 0
    n_zero_sents = 0
    n_filtered_sents = 0

    for idx, entry in enumerate(data):
        before = len(entry.get("candidates", []))
        executable: list = []
        for cand in entry.get("candidates", []):
            fol = cand.get("fol")
            if fol and _z3_parsable(fol, timeout_ms=z3_timeout_ms):
                executable.append(cand)
        after = len(executable)
        total_z3 += after
        if after == 0:
            n_zero_sents += 1
        if after < before:
            n_filtered_sents += 1
        entry["candidates"] = executable
        entry["n_executable"] = after

        if verbose and (idx + 1) % 200 == 0:
            elapsed = time.perf_counter() - t0
            print(f"      [{idx + 1:>4}/{n_sentences}]  "
                  f"cum_exec={total_z3}/{total_dedup}  "
                  f"elapsed={elapsed:.1f}s")

    z3_removed = total_dedup - total_z3
    elapsed = time.perf_counter() - t0

    if verbose:
        print(f"\n  [3] Z3 Filter (timeout={z3_timeout_ms}ms):")
        print(f"      Removed:  {z3_removed} non-executable candidates")
        print(f"      Retained: {total_z3} executable candidates")
        print(f"      Sentences with filtered candidates: {n_filtered_sents}/{n_sentences}")
        print(f"      Sentences with ZERO candidates:     {n_zero_sents}/{n_sentences}")
        print(f"      Avg executable/sentence: {total_z3 / max(n_sentences, 1):.2f}")

    # ---- save (optional) ----
    out_path = paths["out_path"]
    if save_to_disk:
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        size_kb = out_path.stat().st_size / 1024
        if verbose:
            print(f"\n  [4] Saved: {out_path} ({size_kb:.1f} KB)")
    else:
        if verbose:
            print(f"\n  [4] Skipped saving (save_to_disk=False) — data kept in memory")

    if verbose:
        print()
        print("  Summary:")
        print(f"    Input:             {total_in:>6} candidates ({n_sentences} sentences)")
        print(f"    After dedup:       {total_dedup:>6} candidates "
              f"(-{total_in - total_dedup})")
        print(f"    After Z3 filter:   {total_z3:>6} candidates "
              f"(-{total_dedup - total_z3})")
        pct = total_z3 / max(total_in, 1) * 100
        print(f"    Overall retention: {pct:.1f}%")
        print(f"    Sentences with 0 candidates: {n_zero_sents}")
        print(f"    Elapsed: {elapsed:.1f}s")
        print()
        print("  Done. Ready for evaluate_k10 → selection methods.")

    result = {
        "model": model,
        "dataset": dataset,
        "in_path": str(paths["in_path"]),
        "out_path": str(out_path),
        "n_sentences": n_sentences,
        "total_candidates_in": total_in,
        "total_after_dedup": total_dedup,
        "total_after_z3": total_z3,
        "sentences_with_0": n_zero_sents,
        "elapsed_sec": round(elapsed, 1),
    }
    if not save_to_disk:
        result["data"] = data
    return result


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Deduplicate & Z3-filter k10 candidates for downstream selection."
    )
    parser.add_argument("--model", default="Qwen4b",
                        help="Model key: Qwen4b, Qwen8b, Ministral8b")
    parser.add_argument("--dataset", default="val",
                        help="Dataset: val, test, test_folio, test_willow")
    parser.add_argument("--z3-timeout", type=int, default=5_000,
                        help="Z3 parse timeout in ms (default 5000)")
    args = parser.parse_args()

    sys.path.insert(0, str(_ROOT))
    prepare_k10_data(
        model=args.model,
        dataset=args.dataset,
        z3_timeout_ms=args.z3_timeout,
    )


if __name__ == "__main__":
    main()
